DROP TABLE IF EXISTS user;

CREATE TABLE TODO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task VARCHAR(300) NOT NULL,
 id INT status

)


CREATE TABLE Member (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(300) NOT NULL,
    password VARCHAR(300) NOT NULL,
     firstName VARCHAR(300) NOT NULL,
     lastName VARCHAR(300) NOT NULL
)
